### PR TITLE
Update Chinese localization

### PR DESCRIPTION
**Pull request by ZHAY10086**

### CODE REVIEW

**Comment by thevortex** [comment]
awesome thanks!

**Comment by ZHAY10086** [comment]
> awesome thanks!

BTW, is there a way to upload All The Ores lang file? Wanna translate it, but cannot find in GitHub.

**Comment by thevortex** [comment]
i've just set the repo to publicly viewable you should be able to see it now :) I appreciate it!
https://github.com/AllTheMods/AllTheOres/tree/1.18

**Comment by thevortex** [comment]
I invited you to the allthetweaks repo, did you get the invite?

**Comment by ZHAY10086** [comment]
> I invited you to the allthetweaks repo, did you get the invite?

Thanks for your help! I've uploaded the zh_cn.json.

**Pull request merged**
